# Generated by Django 5.0.4 on 2024-05-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='state',
            new_name='status',
        ),
    ]
