# Generated by Django 5.0.4 on 2025-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_state_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top wear'), ('BW', 'Bottom wear'), ('MW', 'Man Wear'), ('WW', 'Women Wear'), ('BW', 'Baby Wear')], max_length=2),
        ),
    ]
