# Generated by Django 5.0.4 on 2025-05-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Topwear', 'Top Wear'), ('Bottomwear', 'Bottom Wear')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MW', 'Man Wear'), ('WW', 'Women Wear'), ('BW', 'Baby Wear'), ('M', 'Mobile'), ('L', 'Laptop')], max_length=2),
        ),
    ]
